//! `authgate init` — an interactive wizard that writes a starter config.
//!
//! Runs locally, once, using filesystem access the operator already has —
//! no network exposure, no bootstrapping problem (unlike a web-based setup
//! GUI, which would need either unauthenticated network-exposed surface or
//! its own separate auth story before OIDC itself is configured).

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use dialoguer::{Input, Password};
use rand::RngExt;

pub fn run(output: &Path) -> Result<()> {
    println!("authgate init — let's set up your first config.\n");

    if output.exists() {
        anyhow::bail!(
            "{} already exists — remove it or pass a different --output path if you want to \
             regenerate it, so this wizard never silently overwrites an existing config",
            output.display()
        );
    }

    let base_domain: String = Input::new()
        .with_prompt("Base domain (e.g. example.com)")
        .interact_text()?;

    let auth_subdomain: String = Input::new()
        .with_prompt("Auth subdomain")
        .default(format!("auth.{base_domain}"))
        .interact_text()?;

    let discovery_url: String = Input::new()
        .with_prompt(
            "OIDC discovery URL (e.g. https://idp.example.com/.well-known/openid-configuration)",
        )
        .validate_with(|input: &String| -> Result<(), String> {
            url::Url::parse(input)
                .map(|_| ())
                .map_err(|e| e.to_string())
        })
        .interact_text()?;

    let client_id: String = Input::new().with_prompt("OIDC client ID").interact_text()?;
    let client_secret: String = Password::new()
        .with_prompt("OIDC client secret")
        .interact()?;

    let first_host: String = Input::new()
        .with_prompt("First app hostname to protect (e.g. app.example.com)")
        .interact_text()?;

    let cookie_signing_key = random_key_hex();
    let refresh_token_encryption_key = random_key_hex();

    let toml = render_config(RenderInput {
        base_domain: &base_domain,
        auth_subdomain: &auth_subdomain,
        discovery_url: &discovery_url,
        client_id: &client_id,
        client_secret: &client_secret,
        first_host: &first_host,
        cookie_signing_key: &cookie_signing_key,
        refresh_token_encryption_key: &refresh_token_encryption_key,
    });

    fs::write(output, toml).with_context(|| format!("failed to write {}", output.display()))?;

    // The file we just wrote embeds secret key material — enforce the same
    // permission requirement `config::load` checks for at startup.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(output, fs::Permissions::from_mode(0o600))
            .with_context(|| format!("failed to chmod 600 {}", output.display()))?;
    }

    println!(
        "\nWrote {} (chmod 600 — it contains secret key material).",
        output.display()
    );
    println!("\nNext steps:");
    println!("  1. Review the generated file and adjust as needed.");
    println!(
        "  2. Point `{auth_subdomain}` and `{first_host}` at this service through Caddy's \
         forward_auth (Phase 10)."
    );
    println!(
        "  3. Run `authgate --config {}` to start the service.",
        output.display()
    );

    Ok(())
}

fn random_key_hex() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill(&mut bytes);
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

struct RenderInput<'a> {
    base_domain: &'a str,
    auth_subdomain: &'a str,
    discovery_url: &'a str,
    client_id: &'a str,
    client_secret: &'a str,
    first_host: &'a str,
    cookie_signing_key: &'a str,
    refresh_token_encryption_key: &'a str,
}

fn render_config(input: RenderInput) -> String {
    let RenderInput {
        base_domain,
        auth_subdomain,
        discovery_url,
        client_id,
        client_secret,
        first_host,
        cookie_signing_key,
        refresh_token_encryption_key,
    } = input;

    format!(
        r#"# Generated by `authgate init`.
# This file contains secret key material — keep it chmod 600 and out of
# version control.

[global]
cookie_signing_key = "{cookie_signing_key}"
refresh_token_encryption_key = "{refresh_token_encryption_key}"
sqlite_path = "authgate.db"

[base_domain."{base_domain}"]
auth_subdomain = "{auth_subdomain}"

[base_domain."{base_domain}".provider]
discovery_url = "{discovery_url}"
client_id = "{client_id}"
client_secret = "{client_secret}"

[host."{first_host}"]
base_domain = "{base_domain}"
"#
    )
}
